config/routes.rb
Rails.application.routes.draw do
  resources :activity_records
  resources :activity_types do
    resources :activity_records
   end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  authenticated :user do
    root :to => 'activity_types#index'
  end
  
  root :to => redirect("/users/sign_in")
end

app/models/activity_record.rb
class ActivityRecord < ApplicationRecord
  belongs_to :activity_type
  belongs_to :user
  validates :description, :quantity, :activity_type_id, presence: true
end

app/models/activity_type.rb
class ActivityType < ApplicationRecord
  has_many :activity_records, dependent: :destroy
  validates :name, :unit, presence: true
  def name_and_quantity
    "#{self.name} (#{self.unit})"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :activity_records, through: :activity_registers
end

app/controllers/activity_records_controller.rb
class ActivityRecordsController < ApplicationController
  before_action :authenticate_user!, :set_activity_record, only: [:show, :edit, :update, :destroy]

  # GET /activity_records
  # GET /activity_records.json
  def index
    @activity_records = ActivityRecord.all.order(date: :desc)
    @route = 'records'
  end

  # GET /activity_records/1
  # GET /activity_records/1.json
  def show
    redirect_to activity_records_url
    @route = 'records'
  end

  # GET /activity_records/new
  def new
    @activity_record = ActivityRecord.new
    @route = 'records'
  end

  # GET /activity_records/1/edit
  def edit
    @route = 'records'
  end

  # POST /activity_records
  # POST /activity_records.json
  def create
    @activity_record = ActivityRecord.new(activity_record_params)
    @activity_record.user = current_user


    respond_to do |format|
      if @activity_record.save
        format.html { redirect_to activity_records_url, notice: 'Activity record was successfully created.' }
        #format.json { render :index, status: :created, location: @activity_record }
      else
        format.html { render :new }
        format.json { render json: @activity_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_records/1
  # PATCH/PUT /activity_records/1.json
  def update
    respond_to do |format|
      if @activity_record.update(activity_record_params)
        format.html { redirect_to activity_records_url, notice: 'Activity record was successfully updated.' }
        #format.json { render :show, status: :ok, location: @activity_record }
      else
        format.html { render :edit }
        format.json { render json: @activity_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_records/1
  # DELETE /activity_records/1.json
  def destroy
    @activity_record.destroy
    respond_to do |format|
      format.html { redirect_to activity_records_url, notice: 'Activity record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_record
      @activity_record = ActivityRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_record_params
      params.require(:activity_record).permit(:date, :description, :quantity, :activity_type_id)
    end
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :authenticate_user!,:set_activity_type, only: [:show, :edit, :update, :destroy]

  # GET /activity_types
  # GET /activity_types.json
  def index
    @activity_types = ActivityType.all
    @route = 'types'
    @records = ActivityRecord.all
  end

  # GET /activity_types/1
  # GET /activity_types/1.json
  def show
    @route = 'types'
    redirect_to activity_types_url
  end

  # GET /activity_types/new
  def new
    @activity_type = ActivityType.new
    @route = 'types'
  end

  # GET /activity_types/1/edit
  def edit
    @route = 'types'
  end

  # POST /activity_types
  # POST /activity_types.json
  def create
    @activity_type = ActivityType.new(activity_type_params)

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to activity_types_url, notice: 'Activity type was successfully created.' }
        #format.json { render :show, status: :created, location: @activity_type }
      else
        format.html { render :new }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activity_types/1
  # PATCH/PUT /activity_types/1.json
  def update
    respond_to do |format|
      if @activity_type.update(activity_type_params)
        format.html { redirect_to activity_types_url, notice: 'Activity type was successfully updated.' }
        #format.json { render :show, status: :ok, location: @activity_type }
      else
        format.html { render :edit }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_types/1
  # DELETE /activity_types/1.json
  def destroy
    @activity_type.destroy
    respond_to do |format|
      format.html { redirect_to activity_types_url, notice: 'Activity type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity_type
      @activity_type = ActivityType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_type_params
      params.require(:activity_type).permit(:name, :unit)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

    
    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}

    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/activity_records_helper.rb
module ActivityRecordsHelper
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/activity_records/_form.html.erb
<style>
/* Added here to stablish priority over default style */
.datepicker-table td.is-today{
    color: #0277bd ;
 }
</style>
<%= form_with(model: activity_record, local: true) do |form| %>
  <% if activity_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_record.errors.count, "error") %> prohibited this activity_record from being saved:</h2>

      <ul>
      <% activity_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date, :class => 'datepicker', :required => true , :placeholder => 'Date of your activity'%>
  </div>

  <div id="answers" class="input-field field">    
    <%= form.collection_select(:activity_type_id ,ActivityType.all, :id, :name_and_quantity) %>
    <label>Select Activity Type</label>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, :required => true, :placeholder => 'running in central park' %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, :required => true, :placeholder => '30 (min)' %>
  </div>

  <div class="actions right">
    <%= form.submit :class => 'btn light-blue darken-3 white-text' %>
  </div>
<% end %>

app/views/activity_records/edit.html.erb
<h5>Editing Activity Record</h5>

<%= render 'form', activity_record: @activity_record %>
<%= link_to 'Back', activity_records_path, :class => 'btn-flat' %>

app/views/activity_records/index.html.erb
<p id="notice"><%= notice %></p>

<row class="center right">
    <%= link_to 'New record', new_activity_record_path, :class => 'btn light-blue darken-3 white-text right-align' %>
</row>
<h5>Activity Records</h5>
<table class=" highlight striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Activity type</th>
      <th>Description</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_records.each do |activity_record| %>
      <tr>
        <td><%= activity_record.date %></td>
        <td><%= activity_record.activity_type.name %></td>
        <td><%= activity_record.description %></td>
        <td><%= activity_record.quantity %> <%= activity_record.activity_type.unit %></td>
        <td><%= link_to(raw("<i class='material-icons grey-text'>edit</i>"), edit_activity_record_path(activity_record)) %></td>
        <td><%= link_to(raw("<i class='material-icons grey-text'>delete</i>"), activity_record, method: :delete, data: { confirm: 'Are you sure?' }) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/activity_records/new.html.erb
<h5>New Activity Record</h5>

<%= render 'form', activity_record: @activity_record %>

<%= link_to 'Back', activity_records_path, :class => 'btn-flat'%>

app/views/activity_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @activity_record.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity_record.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @activity_record.quantity %>
</p>

<p>
  <strong>Activity type:</strong>
  <%= @activity_record.activity_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity_record.user %>
</p>

<%= link_to 'Edit', edit_activity_record_path(@activity_record) %> |
<%= link_to 'Back', activity_records_path %>

app/views/activity_types/_form.html.erb
<%= form_with(model: activity_type, local: true) do |form| %>
  <% if activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity_type.errors.count, "error") %> prohibited this activity_type from being saved:</h2>

      <ul>
      <% activity_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, :required => true, :placeholder => 'Learn to play piano' %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit,  :required => true, :placeholder => 'minutes, km, hours' %>
  </div>

  <div class="actions right">
    <%= form.submit :class => 'btn light-blue darken-3 white-text' %>
  </div>
<% end %>

app/views/activity_types/edit.html.erb
<h5>Editing Activity Type</h5>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Back', activity_types_path, :class => 'btn-flat'  %>

app/views/activity_types/index.html.erb
<p id="notice"><%= notice %></p>

<row class="center right">
    <%= link_to 'New Activity', new_activity_type_path, :class => 'btn light-blue darken-3 white-text right-align' %>
</row>

<h5>Activity Types</h5>

<table class=" highlight striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activity_types.each do |activity_type| %>
      <tr>
        <td><%= activity_type.name %></td>
        <td><%= activity_type.unit %></td>
        <td><%= @records.where(:activity_type => activity_type.id).sum(:quantity).to_s%> <%= activity_type.unit %></td>
        <td><%= link_to(raw("<i class='material-icons grey-text'>edit</i>"), edit_activity_type_path(activity_type)) %></td>
        <td><%= link_to(raw("<i class='material-icons grey-text'>delete</i>"), activity_type, method: :delete, data: { confirm: 'Are you sure?' }) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/activity_types/new.html.erb
<h5>New Activity Type</h5>

<%= render 'form', activity_type: @activity_type %>

<%= link_to 'Back', activity_types_path, :class => 'btn-flat' %>

app/views/activity_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity_type.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @activity_type.unit %>
</p>

<%= link_to 'Edit', edit_activity_type_path(@activity_type) %> |
<%= link_to 'Back', activity_types_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrainingHabits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900|Material+Icons' rel="stylesheet">
    <!-- Compiled and minified CSS  Materialize -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    
  </head>

  <body>
    <div class="navbar-fixed">
    <nav class="light-blue darken-3">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo" style="padding-left: 1.5rem;" >Training Habits</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons white-text">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down nav-items">
          <% if user_signed_in? %>
            <li> <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li>
            <li> <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
          <% else %>
            <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
            <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
          <% end %>
          
        </ul>
      </div>
    </nav>
    </div>
    <%# Side nav to small screen%>
    <ul class="sidenav" id="mobile-demo">
      <% if user_signed_in? %>
      <li class=""><a class="subheader"><span class=" name"><%= current_user.name %></span></a></li>
      <li><a class="subheader"><span class=" email"><%= current_user.email %></span></a></li>
      <li> <%= link_to 'Edit profile', edit_user_registration_path  %> </li>
      <li> <%= link_to "Logout", destroy_user_session_path, method: :delete  %> </li>
      <li><div class="divider"></div></li>
      <li class="<%= 'active' if @route == 'types' %>"><a href="/activity_types">Activities</a></li>
      <li class="<%= 'active' if @route == 'records' %>"><a class="waves-effect" href="/activity_records">Records</a></li>
      
          
      <% else %>
        <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
        <li> <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> </li>
      <% end %>
    </ul>

    <%# Side nav fixed to large screen%>
    <% if user_signed_in? %>
    <ul id="slide-out" class="sidenav sidenav-fixed hide-on-med-and-down" style="top: 64px">
      <li class=""><a class="subheader"><span class=" name"><%= current_user.name %></span></a></li>
      <li><a class="subheader"><span class=" email"><%= current_user.email %></span></a></li>
      <li><div class="divider"></div></li>
      <li class="<%= 'active' if @route == 'types' %>"><a href="/activity_types">Activities</a></li>
      <li class="<%= 'active' if @route == 'records' %>"><a class="waves-effect" href="/activity_records">Records</a></li>
    </ul>
    <% end %>

    <%# Messages to the user%>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>

    <%# Adjust left padding when user signed in%>
    
    <main class="<%= 'padding-left' if user_signed_in? %>">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    

    <!-- Compiled and minified JavaScript Materialize -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

app/views/main/index.html.erb
<div id='main'>
   <app></app>
   <% if user_signed_in? %>
   Logged in as <strong><%= current_user.email %></strong>.
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
   <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
 <% else %>
   <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
   <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
 </p>
</div>